repos:
-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    - id: isort
      exclude: ^(tests/|migrations/)

-   repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
    - id: black
      exclude: ^(tests/|migrations/)
      args: [ --config, pyproject.toml ]

-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      exclude: ^(tests/|migrations/|__init__.py)
      args: [--config, setup.cfg]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
      - id: mypy
        exclude: ^(tests/|migrations/)
        args: [--config, setup.cfg]
