version: "3.4"

services:
  bot_app:
    image: ${IMAGE_APP}
    volumes:
      - ${PWD}/src:/src
    container_name: ${APP_CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENV=${ENV}
    ulimits:
      nofile:
        soft: 4096
        hard: 4096
    restart: always
    logging:
      driver: journald
    env_file:
      - .env
    ports:
      - 127.0.0.1:${PORT_APP}:8000
    depends_on:
      - bot_db

  bot_db:
    image: postgres:12
    container_name: ${DB_CONTAINER_NAME}
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5431:5432"

  bot_redis:
    image: redis:5-alpine
    container_name: ${REDIS_CONTAINER_NAME}
    env_file: .env
    restart: on-failure
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
