version: "3.4"

services:
  bot:
    image: ${IMAGE_APP}
    volumes:
      - ${PWD}/src:/src
    container_name: ${APP_CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENV=${ENV}
    ulimits:
      nofile:
        soft: 4096
        hard: 4096
    restart: always
    logging:
      driver: journald
    env_file:
      - .env
    depends_on:
      - bot_db

  bot_db:
    image: postgres:12
    container_name: ${DB_CONTAINER_NAME}
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5431:5432"

volumes:
  postgres-data:

