version: "3.4"

services:
  bot:
    volumes:
      - ./bot/:/app/bot
      - ./migrations/:/app/migrations
    container_name: ${APP_CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    ulimits:
      nofile:
        soft: 4096
        hard: 4096
    restart: always
    env_file:
      - .env
    ports:
      - ${PORT_APP}:8000
    depends_on:
      - db
      - redis

  db:
    image: postgres:12
    container_name: ${DB_CONTAINER_NAME}
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - ${PORT_DB}:5432

  redis:
    image: redis:5-alpine
    container_name: ${REDIS_CONTAINER_NAME}
    env_file: .env
    restart: on-failure
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
