"""init

Revision ID: 62a9b3a26c25
Revises: 
Create Date: 2022-03-31 18:09:45.393138

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '62a9b3a26c25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('category_name')
    )
    op.create_index(op.f('ix_category_category_id'), 'category', ['category_id'], unique=True)
    op.create_table('completed_task',
    sa.Column('timeshift', sa.SmallInteger(), nullable=True),
    sa.Column('completed_task_id', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.String(), nullable=True),
    sa.Column('completed_time', sa.DateTime(), nullable=True),
    sa.CheckConstraint('timeshift > 0', name='check_positive_timeshift'),
    sa.PrimaryKeyConstraint('completed_task_id')
    )
    op.create_index(op.f('ix_completed_task_completed_task_id'), 'completed_task', ['completed_task_id'], unique=True)
    op.create_table('task',
    sa.Column('timeshift', sa.SmallInteger(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('links', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('planed_time', sa.Date(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.CheckConstraint('timeshift > 0', name='check_positive_timeshift'),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_task_task_id'), 'task', ['task_id'], unique=True)
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.CheckConstraint('user_id > 0', name='check_positive_timeshift'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=True)
    op.create_table('user_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_category')
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_task_task_id'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_completed_task_completed_task_id'), table_name='completed_task')
    op.drop_table('completed_task')
    op.drop_index(op.f('ix_category_category_id'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
