"""add user created at field

Revision ID: 682f3af71a85
Revises: dfde3e5af070
Create Date: 2022-09-07 23:45:20.569478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '682f3af71a85'
down_revision = 'dfde3e5af070'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    # ### end Alembic commands ###
