"""update models

Revision ID: dfde3e5af070
Revises: 1b3aa68145c6
Create Date: 2022-09-07 10:04:29.053079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfde3e5af070'
down_revision = '1b3aa68145c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_category_category_id', table_name='category')
    op.drop_index('ix_completed_task_completed_task_id', table_name='completed_task')
    op.create_unique_constraint(None, 'completed_task', ['task_id'])
    op.add_column('task', sa.Column('planed_start_date', sa.Date(), nullable=True))
    op.add_column('task', sa.Column('planed_end_date', sa.Date(), nullable=True))
    op.drop_index('ix_task_task_id', table_name='task')
    op.drop_column('task', 'planed_time')
    op.add_column('user', sa.Column('timezone', sa.String(length=32), nullable=True))
    op.drop_index('ix_user_user_id', table_name='user')
    op.create_unique_constraint('unique_user_category', 'user_category_associated', ['user_id', 'category_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_category', 'user_category_associated', type_='unique')
    op.create_index('ix_user_user_id', 'user', ['user_id'], unique=False)
    op.drop_column('user', 'timezone')
    op.add_column('task', sa.Column('planed_time', sa.DATE(), autoincrement=False, nullable=True))
    op.create_index('ix_task_task_id', 'task', ['task_id'], unique=False)
    op.drop_column('task', 'planed_end_date')
    op.drop_column('task', 'planed_start_date')
    op.drop_constraint(None, 'completed_task', type_='unique')
    op.create_index('ix_completed_task_completed_task_id', 'completed_task', ['completed_task_id'], unique=False)
    op.create_index('ix_category_category_id', 'category', ['category_id'], unique=False)
    # ### end Alembic commands ###
