"""many

Revision ID: e373af3eeb29
Revises: 62a9b3a26c25
Create Date: 2022-04-01 16:15:17.016589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e373af3eeb29'
down_revision = '62a9b3a26c25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_category_associated',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], )
    )
    op.drop_table('user_category')
    op.add_column('completed_task', sa.Column('task_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'completed_task', 'task', ['task_id'], ['task_id'])
    op.add_column('task', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'user', ['user_id'], ['user_id'])
    op.create_foreign_key(None, 'task', 'category', ['category_id'], ['category_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'category_id')
    op.drop_column('task', 'user_id')
    op.drop_constraint(None, 'completed_task', type_='foreignkey')
    op.drop_column('completed_task', 'task_id')
    op.create_table('user_category',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], name='user_category_category_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='user_category_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_category_pkey')
    )
    op.drop_table('user_category_associated')
    # ### end Alembic commands ###
